package com.mairwunnx.projectessentials

const val SETTING_MAX_FOOD_SATURATION_LEVEL = "feed-max-food-saturation-level"
const val SETTING_MAX_FOOD_LEVEL = "feed-max-food-level"
const val SETTING_AUTO_FLY_MODE_ON_JOIN_ENABLED = "auto-fly-mode-on-join-enabled"
const val SETTING_AUTO_GOD_MODE_ON_JOIN_ENABLED = "auto-god-mode-on-join-enabled"
const val SETTING_TELEPORT_REQUEST_TIMEOUT = "teleport-request-timeout"
const val SETTING_REPLACE_NATIVE_HELP_COMMAND = "replace-native-help-command"
const val SETTING_HELP_COMMAND_MAX_LINES_OUT = "help-command-max-lines-out"
const val SETTING_HELP_COMMAND_COLORIZED_OUT = "help-command-colorized-out"
const val SETTING_FIRST_JOIN_COMMANDS = "first-join-commands"
const val SETTING_AFK_IDLENESS_TIME = "afk-idleness-time"
const val SETTING_AFK_HANDLE_ACTIVITY = "afk-handle-activity"
const val SETTING_DISABLED_COMMANDS = "disabled-commands"
const val SETTING_FLY_WORLDS_DISABLED = "fly-worlds-disabled"
const val SETTING_GOD_WORLDS_DISABLED = "god-worlds-disabled"
